### ISSUE TITLE
Scan should fail if a jqassistant-plugin resource is specifed but not available

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-core-framework#100]
Plugins may provide resources for scanning, this is especially useful for providing shared models:

```yaml
jqassistant:
  plugins:
    - group-id: com.acme.rule
      artifact-id: c4-hexagonal
      version: 1.0.0
  scan:
    include:
      files:
         - jqassistant-plugin:c4-hexagonal.puml
```

The default behavior is that non-existing resources are simply skipped, which makes sense for files of a local file system in a multi-module build - they might exist in any of the modules but the pattern should be specified only once in a config file.

For plugin resources it nevertheless would be helpful that the scan fails: The plugins and the includes are specified because it is expected that they contain specific resources.
In larger setups it is now quite easy that changes in the plugin content might be overseen, therefore it would be helpful that scanning fails in such cases.
