### ISSUE TITLE
Disabling concept or contstraint as maven parameter

### ISSUE THREAD

**Issue by third-bank-of-the-river** [jQAssistant/jqa-core-framework#102]
### Feature Description
It would be very useful to disable/ignore some predefined group criteria or concept that is not valid in certain situation

`-Dsonar.issue.ignore.multicriteria=e1,e2 -Dsonar.issue.ignore.multicriteria.e1.ruleKey=squid:CommentedOutCodeLine -D sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java -Dsonar.issue.ignore.multicriteria.e2.ruleKey=squid:S1607 -D sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
 `

**Comment by DirkMahler** [comment]
Exclusion of constraints if now possible by configuration:

```
jqassistant:
  analyze:
    groups:
       - my-group
     exclude-constraints:
       - constraint-to-be-excluded
```
