### ISSUE TITLE
config property jqassistant.scan.include.files should support file patterns

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqa-core-framework#87]
The config option should support file patterns like this one:
```yaml
jqassistant:
  scan:
    include:
      files:
        - "nexusiq:scan-report::*report.json"
```
